File:       HW4_part_3b.ipynb

Author(s):  Xiongyu Chen

Date:       Jul 15, 2022

In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

-5

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [17]:
'b' in obj2

True

In [18]:
'e' in obj2

False

In [19]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [22]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [23]:
obj4 = pd.Series(sdata, index=states)

In [24]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [25]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [26]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [27]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [30]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [31]:
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [35]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [41]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four',
                             'five', 'six'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [43]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [44]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [45]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [46]:
frame2['debt'] = 16.5

In [47]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [48]:
frame2['debt'] = np.arange(6.)

In [49]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [50]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [51]:
frame2['debt'] = val

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [53]:
frame2['eastern'] = frame2.state == 'Ohio'

In [54]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [56]:
del frame2['eastern']

In [57]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [58]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [59]:
frame3 = pd.DataFrame(pop)

In [60]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [61]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [62]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [63]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [64]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [65]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [66]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [67]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [68]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [69]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [70]:
index = obj.index

In [71]:
index

Index(['a', 'b', 'c'], dtype='object')

In [72]:
index[1:]

Index(['b', 'c'], dtype='object')

In [73]:
labels = pd.Index(np.arange(3))

In [74]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [75]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [76]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [77]:
obj2.index is labels

True

In [78]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [79]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [80]:
'Ohio' in frame3.columns

True

In [81]:
2003 in frame3.index

False

In [82]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [83]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [84]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [85]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [86]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [87]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [88]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [89]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [90]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [91]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index=['a', 'c', 'd'],
                    columns=['Ohio', 'Texas', 'California'])


In [92]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [93]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [94]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [95]:
states = ['Texas', 'Utah', 'California']


In [96]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [98]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [99]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [100]:
new_obj = obj.drop('c')

In [101]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [102]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [103]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])


In [104]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [106]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [107]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [108]:
obj.drop('c', inplace=True)

In [109]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [110]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [111]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [112]:
obj['b']

1.0

In [113]:
obj[1]

1.0

In [114]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [115]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [116]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [117]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [118]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [119]:
obj['b':'c'] = 5

In [120]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [121]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])


In [122]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [123]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [124]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [125]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [126]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [128]:
data[data < 5] = 0

In [129]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [131]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [132]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [133]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [134]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [135]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [136]:
ser = pd.Series(np.arange(3.))
ser
ser[-1]

KeyError: -1

In [137]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [138]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [139]:
ser2[-1]

2.0

In [140]:
ser[:2]

0    0.0
1    1.0
dtype: float64

In [141]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [142]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])


In [143]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [144]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [145]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [147]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])


In [148]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [149]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [150]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [151]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [152]:
df1 = pd.DataFrame({'A': [1, 2]})

In [153]:
df2 = pd.DataFrame({'B': [3, 4]})

In [154]:
df1

A
0  1
1  2

In [155]:
df2

B
0  3
1  4

In [156]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [157]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))

In [158]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))

In [159]:
df2.loc[1, 'b'] = np.nan

In [160]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [161]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [162]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [163]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [164]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [165]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [166]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [167]:
arr = np.arange(12.).reshape((3, 4))

In [168]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [169]:
arr[0]

array([0., 1., 2., 3.])

In [170]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [177]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [178]:
series = frame.iloc[0]

In [179]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [180]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [181]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [182]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [183]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [184]:
series3 = frame['d']


In [185]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [186]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [187]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [188]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])


In [189]:
frame

b         d         e
Utah   -0.084030  0.025746  0.986796
Ohio    0.995118 -0.098418  0.180484
Texas   0.075438 -1.438007 -2.523153
Oregon -1.842127 -0.321967  0.287795

In [190]:
np.abs(frame)

b         d         e
Utah    0.084030  0.025746  0.986796
Ohio    0.995118  0.098418  0.180484
Texas   0.075438  1.438007  2.523153
Oregon  1.842127  0.321967  0.287795

In [191]:
f = lambda x: x.max() - x.min()

In [192]:
frame.apply(f)

b    2.837245
d    1.463753
e    3.509949
dtype: float64

In [193]:
frame.apply(f, axis='columns')

Utah      1.070826
Ohio      1.093536
Texas     2.598591
Oregon    2.129922
dtype: float64

In [194]:
def f(x): 
   return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [195]:
frame.apply(f)

b         d         e
min -1.842127 -1.438007 -2.523153
max  0.995118  0.025746  0.986796

In [196]:
format = lambda x: '%.2f' % x

In [197]:
frame.applymap(format)

b      d      e
Utah    -0.08   0.03   0.99
Ohio     1.00  -0.10   0.18
Texas    0.08  -1.44  -2.52
Oregon  -1.84  -0.32   0.29

In [198]:
frame['e'].map(format)

Utah       0.99
Ohio       0.18
Texas     -2.52
Oregon     0.29
Name: e, dtype: object

In [199]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [200]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [201]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])

In [202]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [203]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [204]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [205]:
obj = pd.Series([4, 7, -3, 2])

In [206]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [207]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [208]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [209]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [210]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [211]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [212]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [213]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [214]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [215]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [216]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [217]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})


In [218]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [219]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [220]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [221]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [222]:
obj.index.is_unique

False

In [223]:
obj['a']

a    0
a    1
dtype: int64

In [224]:
obj['c']

4

In [225]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [226]:
df

0         1         2
a -0.733631 -0.274051 -1.208515
a -0.072373  0.486072  0.078715
b -0.025026  2.461167  1.062596
b  0.251196  1.863936  0.779028

In [227]:
df.loc['b']

0         1         2
b -0.025026  2.461167  1.062596
b  0.251196  1.863936  0.779028

In [228]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                   index=['a', 'b', 'c', 'd'],
                   columns=['one', 'two'])

In [229]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [230]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [231]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [232]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [233]:
df.idxmax()

one    b
two    d
dtype: object

In [234]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [235]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [236]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [237]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [239]:
import pandas_datareader.data as web
all_data = {ticker: web.get_data_yahoo(ticker)
            for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['Volume']
                      for ticker, data in all_data.items()})

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/AAPL/history?period1=1500148800&period2=1657915199&interval=1d&frequency=1d&filter=history
Response Text:
b'<!DOCTYPE html>\n<html lang="zh">\n<head>\n    <meta charset="utf-8">\n    <title>Yahoo</title>\n    <meta name="viewport" content="width=device-width,initial-scale=1,minimal-ui">\n    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n    <style>\nhtml {\n  height: 100%;\n}\nbody {\n  background: #fafafc url(https://s.yimg.com/nn/img/sad-panda-201402200631.png) 50% 50%;\n  background-size: cover;\n  height: 100%;\n  text-align: center;\n  font: 300 16px "helvetica neue", helvetica, verdana, tahoma, arial, sans-serif;\n}\n#message {\n  text-align: left;\n  font-weight: 400;\n  color: #1A1A1A;\n}\n#message a {\n  padding: 0 3px;\n}\n#container {\n  position: absolute;\n  top: 50%;\n  left: 50%;\n  padding: 0 30px;\n  margin-right: -50%;\n  transform: translate(-50%, -50%);\n  max-width: 40em;\n  _width: 40em;\n}\n#container img {\n  width: 174px;\n  height: auto;\n}\n#switcher a {\n  font-weight: 400;\n}\n#switcher a.active {\n  color: #000;\n  text-decoration: none;\n  cursor: default;\n}\n    </style>\n</head>\n<body>\n  <div id="container">\n    <img src="https://s.yimg.com/rz/p/yahoo_homepage_en-US_s_f_p_bestfit_homepage_2x.png" alt="Yahoo Logo">\n    <div id="switcher">\n      <a data-lang="en" class="active" href=\'#\'>English</a> |\n      <a data-lang="zh-Hant" href=\'#\'>\xe7\xb9\x81\xe9\xab\x94\xe4\xb8\xad\xe6\x96\x87</a> |\n      <a data-lang="zh-Hans" href=\'#\'>\xe7\xae\x80\xe4\xbd\x93\xe4\xb8\xad\xe6\x96\x87</a>\n    </div>\n    <div id="message">\n      <p>As of November 1st, 2021 Yahoo\xe2\x80\x99s suite of services will no longer be accessible from mainland China. Yahoo products and services remain unaffected in all other global locations. We thank you for your support and readership.</p>\n    </div>\n  </div>\n<script>\nconst Msg = {\n  \'en\': \'<p>As of November 1st, 2021 Yahoo\xe2\x80\x99s suite of services will no longer be accessible from mainland China. Yahoo products and services remain unaffected in all other global locations. We thank you for your support and readership.</p>\',\n  \'zh-Hant\': \'<p>2021 \xe5\xb9\xb4 11 \xe6\x9c\x88 1 \xe6\x97\xa5\xe8\xb5\xb7\xef\xbc\x8c\xe7\x94\xa8\xe6\x88\xb6\xe5\xb0\x87\xe7\x84\xa1\xe6\xb3\x95\xe5\xbe\x9e\xe4\xb8\xad\xe5\x9c\x8b\xe5\xa4\xa7\xe9\x99\xb8\xe4\xbd\xbf\xe7\x94\xa8 Yahoo \xe7\x9a\x84\xe7\x94\xa2\xe5\x93\x81\xe8\x88\x87\xe6\x9c\x8d\xe5\x8b\x99\xe3\x80\x82\xe9\x80\x99\xe4\xb8\xa6\xe4\xb8\x8d\xe5\xbd\xb1\xe9\x9f\xbf Yahoo \xe5\x9c\xa8\xe5\x85\xa8\xe7\x90\x83\xe5\x85\xb6\xe4\xbb\x96\xe5\x9c\xb0\xe6\x96\xb9\xe7\x9a\x84\xe7\x94\xa2\xe5\x93\x81\xe5\x8f\x8a\xe6\x9c\x8d\xe5\x8b\x99\xe3\x80\x82\xe6\x88\x91\xe5\x80\x91\xe6\x84\x9f\xe8\xac\x9d\xe6\x82\xa8\xe4\xb8\x80\xe7\x9b\xb4\xe4\xbb\xa5\xe4\xbe\x86\xe7\x9a\x84\xe6\x94\xaf\xe6\x8c\x81\xe3\x80\x82</p>\',\n  \'zh-Hans\': \'<p>2021 \xe5\xb9\xb4 11 \xe6\x9c\x88 1 \xe6\x97\xa5\xe8\xb5\xb7\xef\xbc\x8c\xe7\x94\xa8\xe6\x88\xb7\xe5\xb0\x86\xe6\x97\xa0\xe6\xb3\x95\xe4\xbb\x8e\xe4\xb8\xad\xe5\x9b\xbd\xe5\xa4\xa7\xe9\x99\x86\xe4\xbd\xbf\xe7\x94\xa8 Yahoo \xe7\x9a\x84\xe4\xba\xa7\xe5\x93\x81\xe4\xb8\x8e\xe6\x9c\x8d\xe5\x8a\xa1\xe3\x80\x82\xe8\xbf\x99\xe5\xb9\xb6\xe4\xb8\x8d\xe5\xbd\xb1\xe5\x93\x8d Yahoo \xe5\x9c\xa8\xe5\x85\xa8\xe7\x90\x83\xe5\x85\xb6\xe4\xbb\x96\xe5\x9c\xb0\xe6\x96\xb9\xe7\x9a\x84\xe4\xba\xa7\xe5\x93\x81\xe5\x8f\x8a\xe6\x9c\x8d\xe5\x8a\xa1\xe3\x80\x82\xe6\x88\x91\xe4\xbb\xac\xe6\x84\x9f\xe8\xb0\xa2\xe4\xbd\xa0\xe4\xb8\x80\xe7\x9b\xb4\xe4\xbb\xa5\xe4\xbe\x86\xe7\x9a\x84\xe6\x94\xaf\xe6\x8c\x81\xe3\x80\x82</p>\'\n};\n\nconst message = document.querySelector(\'#message\');\n\nconst switchLang = function (lang) {\n  message.innerHTML = Msg[lang] ? Msg[lang] : Msg.en;\n  const oldE = document.querySelector(\'#switcher .active\');\n  const newE = document.querySelector(`#switcher a[data-lang=${lang}]`);\n  oldE.className = \'\';\n  newE.className = \'active\';\n}\n\nconst detectLang = function() {\n  const langs = window.navigator.languages ? window.navigator.languages : [window.navigator.language];\n  const availableLangs = langs.map(l => l.toLowerCase()).filter(l => /^en/.test(l) || /^zh/.test(l));\n  const selectedLang = availableLangs.length ? availableLangs[0] : \'en\';\n  const prefLang =  /^en/.test(selectedLang) ? \'en\' :\n      (selectedLang === \'zh-tw\' || selectedLang === \'zh-hk\') ? \'zh-Hant\' : \'zh-Hans\';\n  switchLang(prefLang);\n}\n\nconst switcher = document.querySelector(\'#switcher\');\nswitcher.addEventListener(\'click\', (e) => {\n  const lang = e.target.getAttribute(\'data-lang\');\n  if (lang) {\n    switchLang(lang);\n  }\n});\n\ndetectLang();\n\n</script>\n</body></html>\n'

In [240]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [241]:
uniques = obj.unique()

In [242]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [243]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [244]:
pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [245]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [246]:
mask = obj.isin(['b', 'c'])

In [247]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [248]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [249]:
unique_vals = pd.Series(['c', 'b', 'a'])

In [250]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2], dtype=int64)

In [251]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                     'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [252]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [253]:
result = data.apply(pd.value_counts).fillna(0)

In [254]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0